version: '3'

services:

  cities:
    image: springio/cities:latest
    ports:
      - "8080:8080"
    container_name: cities_app
    restart: on-failure
    depends_on:
      - cities_db

  cities_db:
    image: mongo:3.6.4
    container_name: cities_db
    expose:
      - 27017
